AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda Function from Cloud Formation'
Parameters:
  FifoQueueName:
    Type: String
    Description: Fifo Queue Name
    Default: "testcf.fifo"
Resources:
  Lambda1:
    Type: "AWS::Lambda::Function"
    Properties: 
        Code:
            S3Bucket: "devops.healthians.co.in"
            S3Key: "tmp/handler.zip"
        Description: Cloud Formation
        FunctionName: testcf
        Handler: main
        ## enter your role arn here
        Role: 'arn:aws:iam::713136746668:role/MyCFLambdaRole'
        Runtime: go1.x
  LambdaFunctionEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !GetAtt MyQueue.Arn
      FunctionName: !GetAtt Lambda1.Arn
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue : true
      QueueName : !Ref FifoQueueName
      DelaySeconds: 0
      VisibilityTimeout: 120
